pipeline:
  build:
    image: ubuntu:xenial
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - apt update
      - apt install -y gcc gcc-avr avr-libc avrdude make git usbutils 
      - lsusb
      - make release -j2
      - make install
      
labels:
  USB: true

