pipeline:
  build:
    image: ubuntu:xenial
    # see https://github.com/docker/docker/issues/19763 to why we use --volumes and not --device
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - apt-get update -qq && apt-get install -qq gcc gcc-avr avr-libc avrdude make git usbutils clang libusb-1.0-0-dev doxygen
      - make release -j2
      - make install
      - lsusb
      - (cd Host/examples/Tester && ./Tester -s )

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: project-hall-flux
    username: drone-ci
    icon_url: https://github.com/drone/brand/raw/master/logos/png/drone-logo_512.png
    when:
     status: [ failure, success ]
     
# Build only on workers that have usb on docker enabled
labels:
  USB: true

