pipeline:
  build:
    image: ubuntu:xenial
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - apt update
      - apt install -y gcc gcc-avr avr-libc avrdude make git usbutils clang  libusb-1.0-0-dev doxygen
      - lsusb
      - make release -j2
      - make install
      - (cd Host/examples/Tester && ./Tester -s )
      
labels:
  USB: true

