language: node_js
node_js:
  - "6"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3.1

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap osx-cross/avr && brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig gcc-avr48 avr-libc48  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod +x setup_env.sh && sudo ./setup_env.sh ; fi

script:
  - chmod +x fetch_submodules.sh && ./fetch_submodules.sh
  - make release
