language: c

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required 
  - os: osx
    osx_image: xcode8.2
    
before_install:
- git submodule update --init --recursive

install:
- pip install -r scripts/requirements.txt
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash scripts/install-node.sh ; fi
  
script:
- make -C Host release -j2
- python scripts/post-build-hook.py --bucket data-chan-js-binaries --upload

notifications:
  slack: fermiumlabs:ngig6ilx4TKXMIZU4dkgFXe9
  email: false
