#remember: $TRAVIS_OS_NAME contains osx or linux

language: c

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode7.3.1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap osx-cross/avr && brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod +x setup_env.sh && sudo ./setup_env.sh ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig node gcc-avr48 avr-libc48 && curl https://www.npmjs.org/install.sh | sh  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod +x install_node.sh  && sudo ./install_node.sh ; fi

script:
  - chmod +x fetch_submodules.sh && ./fetch_submodules.sh
  - make release
