language: node_js

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    node_js:
      - '6'
      - node
    addons:
      apt:
        packages:
          - gcc-avr 
          - avr-libc 
          - binutils-avr
          - libusb-1.0-0-dev 
  - os: osx
    osx_image: xcode8.2	
    node_js:
      - '6'
    
before_install:
- git submodule update --init --recursive

install: 
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap osx-cross/avr && brew update ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 90 brew install swig avr-gcc49 avr-libc49 libusb  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force avr-libc49 avr-gcc49  ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash scripts/install-swig.sh ; fi
  
script:
- make release -j2

notifications:
  slack: fermiumlabs:ngig6ilx4TKXMIZU4dkgFXe9
  email: false
