language: c

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required 
  - os: osx
    osx_image: xcode8.2
    
before_install:
- git submodule update --init --recursive

install:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then pip install GitPython requests tinys3; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash scripts/install-node.sh ; fi
  
script:
- make -C Host release -j2
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python scripts/trigger-wercker.py; fi

notifications:
  slack: fermiumlabs:ngig6ilx4TKXMIZU4dkgFXe9
  email: false
