language: c

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required 
  - os: osx
    osx_image: xcode8.2
    
install:
- pip install -r scripts/requirements.txt
  
script:
- make -C Host release -j2

after_success:
- python scripts/post-build-hook.py --bucket data-chan-js-binaries --upload

notifications:
  slack: fermiumlabs:ngig6ilx4TKXMIZU4dkgFXe9
  email: false
