#remember: $TRAVIS_OS_NAME contains osx or linux

language: c

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode7.2

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - python-dev
      - gcc
      - g++

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi

install: make get-deps python byacc flex autogen autoconf gcc-avr avr-libc wget

script:
  - make release
