#remember: $TRAVIS_OS_NAME contains osx or linux

language: c

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode7.3.1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap osx-cross/avr && brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod +x setup_env.sh && sudo ./setup_env.sh ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig node gcc-avr48 avr-libc48 && curl https://www.npmjs.org/install.sh | sh  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export NODE_VER=6.9.1 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash nodesource_setup.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y nodejs ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export NVM_DIR="/root/.nvm" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then . $NVM_DIR/nvm.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nvm install $NODE_VER ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nvm alias default $NODE_VER ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nvm use default ; fi

script:
  - chmod +x fetch_submodules.sh && ./fetch_submodules.sh
  - make release
