language: node_js

  
  
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    node_js:
      - '6'
    addons:
      apt:
        packages:
          - gcc-avr 
          - avr-libc 
          - binutils-avr
          - avrdude 
          - libusb-1.0-0-dev 
  - os: osx
    osx_image: xcode7.3.1
    node_js:
      - '6'
    
before_install:
- git submodule update --init --recursive

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap osx-cross/avr && brew update ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig gcc-avr48 avr-libc48  ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash scripts/install-swig.sh ; fi
  
script:
- make release

notifications:
  email: false
  slack:
    on_success: always
    secure: PyZmCZ8RrkUOJ/xgihrTB6bAGfDpSETzNy+7yErLTE7RzpzqNirG2YMCcFFPo5outZC28RwiElu+0yAypHiU3kTxn7xfOBJGfATUVYtShuiLskt6uvhJT+zsDVXsQHgDAjcOcRe8gT89KUeZ0bxCQLbPJH2nbtYvmj32gXVJakBMqHp84ZkON/ZUt90S62haqMdrTULDudNrQpWghB+9aIDtAcaCEx0Of0bGKoeMV7Ni0EX/w07d22KDHCk2soinHzuKwTulQoANlARVIc9qbw8NaFZe/nn0czxgna9sm3///9nrtPRr/tn7OJHyXZkbnJsjBo26Np64x34X7kNfzWZifLbDKhtQOntRCaXTTxpKHCOOmCbBNzlXjUAquhxppGUQba0ECwi9gm0/aImgmjz9qjkEqnz8JDXbmR5fGpcLrBgweAmANbBPft7Zwfvz48i7T66DO06dR5GwOQp1Sb/FG+90fvcO5kSQyth+lHWwFCiB9EgRYa4anNaLPi9XlwwIpSexEDECjvw9zMI8ORv9yjC5awIkCXR7V95+MgfL/DWRoQ2g4AkJXbizyqHBwA0Oq7eYJR6WY/6njQmartqyWB2bJk4t7img6J38i6X6fJTxZRc7VPEtwB3gUB++x4G5cifIk0eOUyaryyjS1Alh8QeUqCx7cgoIEnNcOic=
