#remember: $TRAVIS_OS_NAME contains osx or linux

language: c

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: xcode8.2

addons:
  apt:
    packages:
      - build-essential
      - libpcre3
      - libpcre3-dev
      - libusb-1.0-0-dev
      - python-dev
      - gcc
      - g++
      - python
      - byacc
      - flex
      - autogen
      - autoconf
      - gcc-avr
      - avr-libc
      - wget
      - curl
      - make

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig    ; fi

install:

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo chmod +x install_swig.sh && sudo ./install_swig.sh ; fi
  - chmod +x fetch_submodules.sh && ./fetch_submodules.sh
  - make release
