language: c

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - libstdc++6

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required 
  - os: osx
    osx_image: xcode8.2
    
before_install:
- git submodule update --init --recursive

install:
- pip install GitPython requests tinys3
- sudo bash scripts/install-node.sh

  
script:
- make -C Host release -j2
- python scripts/trigger-wercker.py

notifications:
  slack: fermiumlabs:ngig6ilx4TKXMIZU4dkgFXe9
  email: false
