language: c

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode8.2

install:
- pip install --user -r scripts/requirements.txt

script:
- make -C Host release -j2
-  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L **/libDataChan.dylib  ; fi
-  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then install_name_tool -change "/usr/local/opt/libusb/lib/libusb-1.0.0.dylib" "@rpath/libusb/libusb.dylib" **/libDataChan.dylib  ; fi
-  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L **/libDataChan.dylib  ; fi


after_success:
- python scripts/post-build-hook.py --bucket data-chan-libs --upload

notifications:
  slack: fermiumlabs:ngig6ilx4TKXMIZU4dkgFXe9
  email: false
