language: c

addons:
  apt:
    packages:
      - libusb-1.0-0-dev

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required 
  - os: osx
    osx_image: xcode8.2
    
before_install:
- git submodule update --init --recursive

install:
  
script:
- make -C Host release -j2

publish:
- (cd Host/NODEJS_API/ && npm run publish-libraries)

notifications:
  slack: fermiumlabs:ngig6ilx4TKXMIZU4dkgFXe9
  email: false
