version: 1.0.{build}

before_build:
- ps: git submodule update --init --recursive -q
- cinst make
- cinst mingw
- cinst msys2
- cinst 7zip.install
- cinst wget
- ps: $env:Path += ";C:\tools\mingw64\bin\"
- ps: refreshenv


build_script:
- ps: wget https://netcologne.dl.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.21/libusb-1.0.21.7z -O libusb-1.0.21.7z
- ps: mkdir libusb-1.0.21
- ps: Get-ChildItem libusb-1.0.21.7z | % {& "C:\Program Files\7-Zip\7z.exe" "x" $_.fullname "-olibusb-1.0.21"}
- ps: Copy-Item libusb-1.0.21/MinGW64/static/libusb-1.0.a C:\tools\mingw64\x86_64-w64-mingw32\lib\
- ps: New-Item C:\tools\mingw64\x86_64-w64-mingw32\include\libusb-1.0 -type directory
- ps: Copy-Item libusb-1.0.21/include/libusb-1.0/libusb.h C:\tools\mingw64\x86_64-w64-mingw32\include\libusb-1.0\
- ps: make -C Host release

after_build:
- ps: pip install -r scripts/requirements.txt
- ps: python scripts/post-build-hook.py --bucket data-chan-js-binaries --upload

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: project-hall-flux
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
