version: 1.0.{build}
environment:
  AVR_GCC_URL:
    secure: vsQ1I0nVqCdmBQpLX5ldU0+6JCqK+miFlLxKs+diY4RbjdbQEb900+PJQpfI9zZ1bbB4o5DH+5i43eM9SZR9HOXvJuUgxZVarPkC/6qHkhZ6ZDXH1+zSy8p9K0DVRtDM


before_build:
- ps: git submodule update --init --recursive -q
- ps: choco install make
- cmd: curl -fsS -o avr-gcc.zip %AVR_GCC_URL%
- ps: Expand-Archive avr-gcc.zip -DestinationPath "C:\Program Files (x86)"
- ps: $env:Path += ";C:\Program Files (x86)\avr-gcc\bin\"
- echo %path:;=&echo.%

build_script:
- ps: make -C Device Release
- ps: make -C Host Release

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: project-hall
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
