version: 1.0.{build}

before_build:
- ps: git submodule update --init --recursive -q
- ps: choco install make
- ps: choco install mingw
- ps: choco install msys2
- ps: choco install curl
- ps: choco install 7zip.install
- ps: refreshenv
- ps: $env:Path += ";C:\Program Files (x86)\avr-gcc\bin\"


build_script:
- ps: curl https://vorboss.dl.sourceforge.net/project/libusb/libusb-1.0/libusb-1.0.20/libusb-1.0.20.7z --output libusb-1.0.20.7z
- ps: mkdir libusb-1.0.20
- ps: Get-ChildItem libusb-1.0.20.7z | % {& "C:\Program Files\7-Zip\7z.exe" "x" $_.fullname "-olibusb-1.0.20"}
- ps: ls libusb-1.0.20
- ps: make -C Host release -j2

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: project-hall
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
