version: 1.0.{build}
before_build:
- ps: choco install make
build_script:
- ps: make release
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: project-hall
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
