site_name: data-chan
repo_url: https://github.com/NeroReflex/data-chan

pages:
- Home: index.md
- FAQ: faq.md
- Build: build.md
- Install: install.md
- Library API:
    - Getting Started: library_usage/get_started.md
    - API Documentation: API_Documentation.md
- Protocol: 
    - Specifications: protocol.md
    - IN Packets:
        - Measure:    IN_packets/measure.md
        - Async Response: IN_packets/async_response.md
    - OUT Packets:
        - Sync Request:    OUT_packets/sync_request.md
        - Async Request:    OUT_packets/async_request.md
- Deploy: deploy.md
theme: readthedocs
