site_name: data-chan
repo_url: https://github.com/NeroReflex/data-chan

pages:
- Home: index.md
- Build: build.md
- Protocol: protocol.md
- IN Packets:
    - Measure:    IN_packets/Measure.md
- FAQs: faq.md

theme: readthedocs
